### PR TITLE
Issue 3

### PR DESCRIPTION
**Pull request by DaevMithran**
To raise a new Pull Request, the following prerequisites need to be met. Please tick before proceeding:

- [x] a conversation was held in the appropriate [DRMAN discord] channel.
- [x] a Github Issue #3 was opened for this feature / bug  .

The current code 

- creates an organization if it doesn't exists
- creates a repository
- added branch and signature protections for the repository
- commits a genesis transaction 
      - with an admin folder
      - where the creator's DID folder is created

### CODE REVIEW

**Review by panickervinod — COMMENTED** [review]
@DaevMithran do refactor all script file under src/main/bash folder , 

Other suggested refactoring are:.
1. Move core and common VCR handling script to helper, Github/Gitlab specific capabilies would reside in the respective plugins.
2. Introduce a capablity to include plugins  in the  corresponding folder structure post install of DRman. This can also happen later using DRman command/script to install xxx plugin
3. Group multiple function signatures i.e for create, delete , validate, reset etc for a XXX VCR in a single xxx-plugin script.
4. Create the common DRman plugin template with generic functions like create, delete, validate, reset etc.

**Comment by DaevMithran** [comment]
> @DaevMithran do refactor all script file under src/main/bash folder ,

@panickervinod only my changes or the overall code in general ?

**Comment by DaevMithran** [comment]
@panickervinod sound's good. Will work on it

**Comment by DaevMithran** [comment]
@panickervinod  can we merge the current code? I'll create separate pull requests for further developments.

**Comment by DaevMithran** [comment]
Code changes

- Creates an admin and member teams when are repository is created by default e.g. REPONAME_ADMIN, REPONAME_MEMBER
- Added feature to resolve a DID

**Comment by panickervinod** [comment]
@DaevMithran Please can you also fix the naming convention for the function names  . 
i.e the function names have a prefix of "__drm_"  @arunprakashpj

**Pull request closed without merging**
